[package]
name = "phala-serde-more"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.130", default-features = false, features = ["derive", "alloc"] }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false }

[dev-dependencies]
serde_cbor = "0.11.2"

[features]
default = ["std", "crypto"]
crypto = ["sp-core/full_crypto"]
std = [
    "sp-core/std",
]
