[package]
name = "pink-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
pink-capi = { path = "../capi" }
pink-chain-extension = { path = "../chain-extension" }
phala-crypto = { path = "../../phala-crypto" }
serde = { version = "1", features = ["derive"] }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
im = { version = "15", features = ["serde"] }
once_cell = "1"
libc = "0.2"
log = "0.4"
tracing = "0.1"
environmental = "1"
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
pink-runtime = { path = "../runtime", default-features = false }

[dev-dependencies]
pink-runtime = { path = "../runtime" }
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = [
    "derive",
] }
insta = "1"
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
env_logger = "0.10.0"
assert_matches = "1.5.0"
