# workaround for https://github.com/rust-lang/cargo/issues/6745
[workspace]

[package]
edition = "2021"
name = "sideprog"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.16"
once_cell = "1.10.0"
sidevm = { version = "0.2.0-alpha.7" }
tokio = { version = "1", features = ["macros"] }
futures = "0.3"
hex_fmt = "0.3"
sideabi = { path = "../sideabi" }
serde_json = "1.0"
scale = { package = "parity-scale-codec", version = "3" }
